### ISSUE TITLE
wav头结构ex_size的疑问

### ISSUE THREAD

**Issue by i-square** [JarvisChu/PCM2Wave#1]
你好，

我看到你的wav header定义里的SubChunkFormat，其中有一个`uint16_t ex_size;`
请问这个字段的来源是什么呢？我查了[wav格式的定义](http://soundfile.sapp.org/doc/WaveFormat/) 并没有看到相关描述
希望解惑

谢谢~

**Comment by JarvisChu** [comment]
参考文章：https://juejin.cn/post/6844904051964903431

> WAV扩展
    有一些WAV的头部并不仅仅只有44个字节，比如通过FFmpge编码而来的WAV文件头部信息通常大于44个字节。这是因为根据WAV规范，其头部还支持携带附加信息，所以只按照44个字节的长度去解析WAV头部信息是不一定正确的，还需要考虑附加信息。那么如何知道一个WAV文件头部是否包含附加信息呢？
  根据"fmt "子块长度来判断即可。

以及文章：https://www.cnblogs.com/wangguchangqing/p/5957531.html

> 关于扩展格式块
当WAV文件使用的不是PCM编码方式是，就需要扩展格式块，它是在基本的Format chunk又添加一段数据。该数据的前两个字节，表示的扩展块的长度。紧接其后的是扩展的数据区，含有扩展的格式信息，其具体的长度取决于压缩编码的类型。当某种编码方式（如 ITU G.711 a-law）使扩展区的长度为0，扩展区的长度字段还必须保留，只是其值设置为0。

**Comment by i-square** [comment]
你好，

感谢提供2篇参考文章，之前我确实忽略了，一直在找PCM编码的wav头定义
使用pcm编码时wav头应该还是按照标准的44字节：[pcm编码wav格式的定义](http://soundfile.sapp.org/doc/WaveFormat/)

我又查了下非PCM编码的wav头定义，以供参考：

仅非PCM编码格式的wav头才需要一个额外字段来表达，参考[Audio File Format Specifications](http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/WAVE/WAVE.html)的Non-PCM Formats部分

> Non-PCM Formats
> An extended Format chunk is used for non-PCM data. The field gives the size of the extension.cbSize
>
> - For **all formats other than PCM**, the Format chunk must have an extended portion. The extension can be of zero length, but the size field (with value 0) must be present.

ex_size的字节数也跟具体编码格式相关，不一定是2字节，具体可参考[这篇文章](https://www.cnblogs.com/ranson7zop/p/7657874.html)的表4

因为这个repo是pcm转wav，因此建议还是按照标准44字节头定义，以免产生歧义

谢谢~
